typedef struct prod Produto;
Produto* criarProduto(char nome[], float preco, int estoque);
Produto* consultarProduto(Produto* raiz, char nome[]);
void atualizarProduto(Produto* raiz, char nome[], float preco, int estoque);
Produto* removerProduto(Produto* raiz, char nome[]);
void listarProdutos(Produto* raiz);
int contarNos(Produto* raiz);
void listarFolhas(Produto* raiz);
int calcularAltura(Produto* raiz);
void liberarMemoria(Produto* raiz);
char*getNome(Produto* produto);
void setNome(Produto* produto, char nome[]);
float getPreco(Produto* produto);
void setPreco(Produto* produto, float preco);
int getEstoque(Produto* produto);
void setEstoque(Produto* produto, int estoque);
struct prod* getEsq(Produto* produto);
void setEsq(Produto* produto, Produto* esq);
struct prod* getDir(Produto* produto);
void setDir(Produto* produto, Produto* dir);
